---
title: "Experiment 7: DC Bikeshare Data"
subtitle: "Effect of rain on ridership" 
date: 2023-11-06
output: html_notebook
---

#Packages 
```{r}
library(tidyverse)
library(janitor)
library(here)
library(plotly)
library(openmeteo)
```

###Other Project Defaults
```{r}
theme_set(theme_minimal())
```

```{r}
bikes <- here("data_raw", "202309-capitalbikeshare-tripdata.csv")

dfbikes <- read_csv(bikes) |> clean_names()
```
```{r}
df2s = dfbikes |>
  select(rideable_type, member_casual, contains("start"), ride_id)|>
  mutate(start_stop = "start") |>
           rename(t = started_at, 
                  station_name = start_station_name,
         station_id = start_station_id,
         lat= start_lat,
         lng=start_lng
         )
```

```{r}
df2e=dfbikes %>% 
  select(ride_id,rideable_type,member_casual,
                    contains("end")) %>%
  mutate(start_stop="stop") %>%
  rename(t=ended_at,
         station_name=end_station_name,
         station_id=end_station_id,
         lat=end_lat,
         lng=end_lng)
```
```{r}
df2s = dfbikes |>
  select(rideable_type, member_casual, contains("start"), ride_id)|>
  mutate(start_stop = "start") |>
           rename(t = started_at, 
                  station_name = start_station_name,
         station_id = start_station_id,
         lat= start_lat,
         lng=start_lng
         )
```

```{r}
df2e=dfbikes %>% 
  select(ride_id,rideable_type,member_casual,
                    contains("end")) %>%
  mutate(start_stop="stop") %>%
  rename(t=ended_at,
         station_name=end_station_name,
         station_id=end_station_id,
         lat=end_lat,
         lng=end_lng)
```

```{r}
df2s=dfbikes %>% 
  select(rideable_type,member_casual,
                    contains("start"),ride_id) %>% 
  mutate(start_stop="start") %>%
  rename(t=started_at,
         station_name=start_station_name,
         station_id=start_station_id,
         lat=start_lat,
         lng=start_lng)

df2e=dfbikes %>% 
  select(ride_id,rideable_type,member_casual,
                    contains("end")) %>%
  mutate(start_stop="stop") %>%
  rename(t=ended_at,
         station_name=end_station_name,
         station_id=end_station_id,
         lat=end_lat,
         lng=end_lng)
 
df2=bind_rows(df2s,df2e) %>%
  arrange(t) %>%
  mutate(rider_delta=(start_stop=="start")*2-1) %>% #change in ridership 
  mutate(riders=cumsum(rider_delta)) %>%
  relocate(riders,.after=t)


```

#Full month
```{r}
df2 %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```

# Constructing a Subsampled dataset

```{r}
df_s=df2 |> slice_head(n=1000)
```

```{r}
df_s %>% 
  ggplot(aes(t,riders)) +
  geom_point()
```

```{r}
df_e=df_s |>
  mutate(t_f=floor_date(t, "10 mins")) |>
  relocate(t_f, .after=t) |>
  slice_head(n=1, by= t_f)
```

```{r}
df_e %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```

```{r}
df_r=df2 |>

  mutate(t_f=floor_date(t,"10 mins")) %>%

  relocate(t_f,.after=t) %>%

  slice_head(n=1,by=t_f)
```

```{r}
df_r %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```
```{r}
p1=df2 %>% 
  filter(day(t)==18) %>%
  ggplot(aes(t,riders)) +
  geom_line() +
  ggtitle("Riders on 18Sep")

p1+
  geom_line(data=df_r %>% filter(day(t)==18),
  color="red")
```
```{r}
df_r=df2 |>
  mutate(t_f=floor_date(t,"1 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)
```

```{r}
df_w=weather_history("Washington",
                    start = "2023-09-01",
                    end = "2023-09-30",
                    hourly = c("apparent_temperature",
                               "wind_speed_10m",
                               "precipitation")
)
```

```{r}
df_w %>% 
  ggplot(aes(datetime, hourly_precipitation)) +
  geom_line()
```

```{r}
df_r %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```
```{r}
df_w = df_w |>
  mutate(with_tz(datetime, "UTC"))

df_w$datetime[1:10]
```

```{r}
df_j=df_s %>% left_join(df_w,
                        by=join_by(closest(t>=datetime)))
```

```{r}
df_j=df_s %>% 
  left_join(df_w,by=join_by(closest(t>=datetime)))  %>%
  relocate(datetime, .after=t)
 
head(df_j)
```

```{r}
df2$t[1:5]
force_tz(df2$t[1:5],"America/New_York")
```

```{r}
df2c=df2 %>% mutate(t=force_tz(t,tzone="America/New_York")) #corrected
 
df_s2=df2c %>% slice_sample(n=1000)
 
df_j2=df_s2 %>% 
  left_join(df_w,by=join_by(closest(t>=datetime)))  %>%
  relocate(datetime, .after=t)
 
head(df_j2)
```

```{r}
dfc = df2c |>
  left_join(df_w, by = join_by(closest(t>=datetime))) |>
  relocate(datetime, .after=t) |>
  rename(atemp = hourly_apparent_temperature, 
         wind = hourly_wind_speed_10m,
         prec = hourly_precipitation)
```

```{r}
p2 = dfc |>
  ggplot(aes(t,riders,color = prec > 1)) +
  geom_point()
```


```{r}
p2
```

```{r}
p3=dfc %>% 
  filter(day(t)==18) %>%
  ggplot(aes(t,riders, color = prec)) +
  geom_point() +
  ggtitle("Rain on 18Sep")

p3
```

```{r}
p4=dfc %>% 
  filter(day(t)==10) %>%
  ggplot(aes(t,riders, color = prec)) +
  geom_point() +
  ggtitle("Rain on 10Sep")

p4
```

```{r}
p5=dfc %>% 
  filter(day(t)==23) %>%
  ggplot(aes(t,riders, color = wind, shape = rideable_type )) +
  geom_point() +
  ggtitle("Rain on 10Sep")

p5
```

```{r}
ggplotly(p2)
```

```{r}
df1_d=dfbikes %>%
  mutate(ride_time = ended_at-started_at)
```

